### ISSUE TITLE
Configure from toml

### ISSUE THREAD

**Issue by robiot** [robiot/zash#11]
Example toml:
```toml
[Helper]
CompletionType = "list"
EditMode = "emacs"
OutputStream = "stdout"

[History]
Path = "$HOME/.zash_history"
IgnoreSpaces = true

[Shell]
Prompt = "({username}.blue)@({hostname}.blue) ({pwd}.cyan) (•.blue)(•.red)(•.yellow)"
```
